### ISSUE TITLE
Netdisco docker image with docker-compose doesnt work

### ISSUE THREAD

**Issue by Ondjultomte** [netdisco/netdisco-docker#22] opened 2019-07-25 11:54 UTC
Followed these instructions

Only if you are on Linux:

sudo groupadd netdisco -g 901
sudo useradd -u 901 -p x -g netdisco netdisco
mkdir -p netdisco/{logs,config,nd-site-local}
sudo chown -R netdisco:netdisco netdisco

And then (for everyone):

curl -Ls -o docker-compose.yml https://tinyurl.com/nd2-dockercompose
docker-compose up

and it failes:

$ sudo docker-compose up
Creating netdisco_netdisco-postgresql_1 ... done
Creating netdisco_netdisco-web_1        ... done
Creating netdisco_netdisco-backend_1    ... done
Attaching to netdisco_netdisco-postgresql_1, netdisco_netdisco-backend_1, netdisco_netdisco-web_1
netdisco-postgresql_1  | netdisco-db-entrypoint: starting pg privately to container
netdisco-postgresql_1  | pg_ctl: another server might be running; trying to start server anyway
netdisco-postgresql_1  | waiting for server to start....LOG:  could not bind IPv6 socket: Address not available
netdisco-postgresql_1  | HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.
netdisco-postgresql_1  | LOG:  database system was interrupted; last known up at 2019-07-25 11:31:13 UTC
netdisco-postgresql_1  | LOG:  database system was not properly shut down; automatic recovery in progress
netdisco-postgresql_1  | LOG:  invalid record length at 0/1952350: wanted 24, got 0
netdisco-postgresql_1  | LOG:  redo is not required
netdisco-postgresql_1  | LOG:  MultiXact member wraparound protections are now enabled
netdisco-postgresql_1  | LOG:  database system is ready to accept connections
netdisco-postgresql_1  | LOG:  autovacuum launcher started
netdisco-postgresql_1  |  done
netdisco-postgresql_1  | server started
netdisco-postgresql_1  | netdisco-db-entrypoint: bringing schema up-to-date
netdisco-postgresql_1  | netdisco-db-entrypoint: importing OUI
netdisco-postgresql_1  | netdisco-db-entrypoint: marking schema as up-to-date
netdisco-postgresql_1  | netdisco-db-entrypoint: adding admin user if none exists
netdisco-postgresql_1  | netdisco-db-entrypoint: adding session key if none exists
netdisco-postgresql_1  | netdisco-db-entrypoint: queueing stats job
netdisco-postgresql_1  | INSERT 0 1
netdisco-postgresql_1  | netdisco-db-entrypoint: shutting down pg (will restart, listening for clients)
netdisco-postgresql_1  | waiting for server to shut down....LOG:  received fast shutdown request
netdisco-postgresql_1  | LOG:  aborting any active transactions
netdisco-postgresql_1  | LOG:  autovacuum launcher shutting down
netdisco-postgresql_1  | LOG:  shutting down
netdisco-postgresql_1  | LOG:  database system is shut down
netdisco-backend_1     | Attempting to create directory /home/netdisco/perl5
netdisco-web_1         | Attempting to create directory /home/netdisco/perl5
netdisco-backend_1     | error: cannot find Netdisco config at /home/netdisco/perl5/lib/perl5/auto/share/dist/App-Netdisco/environments/deployment.yml or /home/netdisco/environments/deployment.yml
netdisco_netdisco-backend_1 exited with code 2
netdisco-web_1         | error: cannot find Netdisco config at /home/netdisco/perl5/lib/perl5/auto/share/dist/App-Netdisco/environments/deployment.yml or /home/netdisco/environments/deployment.yml
netdisco_netdisco-web_1 exited with code 2
netdisco-postgresql_1  |  done
netdisco-postgresql_1  | server stopped
netdisco-postgresql_1  | LOG:  database system was shut down at 2019-07-25 11:52:28 UTC
netdisco-postgresql_1  | LOG:  MultiXact member wraparound protections are now enabled
netdisco-postgresql_1  | LOG:  database system is ready to accept connections
netdisco-postgresql_1  | LOG:  autovacuum launcher started

**Comment by inphobia** [comment] 2019-08-06 20:22
heya, we are still in the proces of getting our docker images a bit more stable but are finding it hard to reproduce certain issues. could you create an issue is in this bug tracker instead? it has container specific info requests which we need to figure out the root problem.

currently it seems like a a missing file or a race condition in the startup sequence.

i've reworked most of the config and it al least runs on my windows 10 workstation, but file sharing between host & containers is tricky due to how i set it up. all feedback welcome:
https://github.com/inphobia/netdisco-docker/tree/nn_dockerwin

**Comment by jinho10** [comment] 2019-09-24 18:40
I have the similar issue. Even after I update the db schema from inside container (in the backend, ran netdisco-deploy again to reset the db schema, etc.), the problem persists. The db does not seem to have any issue when I connect to it and see the contents. I also see the entry in admin table is created when I add something in the UI side.. but the queued job has never been executed. The error message keeps showing the db connection issue. 

## ==> netdisco-backend.log <==
DBIx::Class::Schema::Versioned::_on_connect(): Your DB is currently unversioned. Please call upgrade on your schema to sync the DB. at /home/netdisco/perl5/lib/perl5/DBICx/Sugar.pm line 121
DBIx::Class::Storage::DBI::catch {...} (): DBI Connection failed: DBI connect('dbname=netdisco;host=netdisco-postgresql','netdisco',...) failed: could not connect to server: Connection refused
	Is the server running on host "netdisco-postgresql" (172.20.0.3) and accepting
	TCP/IP connections on port 5432? at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 1517. at /home/netdisco/perl5/lib/perl5/App/Netdisco/JobQueue/PostgreSQL.pm line 50

## ==> netdisco-web.log <==
Child process 110 exited with status 255
[119] 2019-09-24 18:36:11  warn App::Netdisco 2.043001 web
[122] 2019-09-24 18:36:11  warn App::Netdisco 2.043001 web
DBIx::Class::Schema::Versioned::_on_connect(): Your DB is currently unversioned. Please call upgrade on your schema to sync the DB. at /home/netdisco/perl5/lib/perl5/DBICx/Sugar.pm line 121
Error while loading /home/netdisco/perl5/bin/netdisco-web-fg: The setting session_cookie_key must be defined at /home/netdisco/perl5/lib/perl5/Dancer/Session/Cookie.pm line 38.
Compilation failed in require at /home/netdisco/perl5/bin/netdisco-web-fg line 53.
BEGIN failed--compilation aborted at /home/netdisco/perl5/bin/netdisco-web-fg line 53.
Child process 115 exited with status 255
[123] 2019-09-24 18:36:11  warn App::Netdisco 2.043001 web

**Comment by collinsry** [comment] 2020-01-31 20:54
I am experiencing this same issue on a brand new install (on CentOS 7.7).

I see the same messages in the log files as the most recent comment.

Running docker-compose up -d seems to work. I am able to connect to the web GUI and add devices, but it does not discover any neighbors and some jobs sit in queued status unless the system is rebooted.

**Comment by StewAlexanderACC** [comment] 2020-03-03 16:00
Read my install guide here: [NetDisco Install Docker PDF](https://github.com/StewAlexanderACC/NetDisco-Ubuntu-Install/blob/master/NetDisco-New%20-%20Support.pdf)

I got the above to work

**Comment by wuleiisme** [comment] 2020-04-18 11:09
same issue...

**Comment by manualbashing** [comment] 2020-06-05 17:27
Same issue on Ubuntu 20.04.

The webinterface is running and responsive, but no discovery jobs ever finish.

## netdisco-backend.log

DBIx::Class::Schema::Versioned::_on_connect(): Your DB is currently unversioned. Please call upgrade on your schema to sync the DB. at /home/netdisco/perl5/lib/perl5/DBICx/Sugar.pm line 121
DBIx::Class::Storage::DBI::catch {...} (): DBI Connection failed: DBI connect('dbname=netdisco;host=netdisco-postgresql','netdisco',...) failed: could not connect to server: Connection refused
        Is the server running on host "netdisco-postgresql" (172.20.0.2) and accepting
        TCP/IP connections on port 5432? at /home/netdisco/perl5/lib/perl5/DBIx/Class/Storage/DBI.pm line 1517. at /home/netdisco/perl5/lib/perl5/App/Netdisco/JobQueue/PostgreSQL.pm line 50

## netdisco-web.log

DBIx::Class::Schema::Versioned::_on_connect(): Your DB is currently unversioned. Please call upgrade on your schema to sync the DB. at /home/netdisco/perl5/lib/perl5/DBICx/Sugar.pm line 121
Child process 10 exited with status 115
Error while loading /home/netdisco/perl5/bin/netdisco-web-fg: The setting session_cookie_key must be defined at /home/netdisco/perl5/lib/perl5/Dancer/Session/Cookie.pm line 38.
Compilation failed in require at /home/netdisco/perl5/bin/netdisco-web-fg line 53.
BEGIN failed--compilation aborted at /home/netdisco/perl5/bin/netdisco-web-fg line 53.
Child process 11 exited with status 115
[19] 2020-06-05 17:18:25  warn App::Netdisco 2.045006 web
[18] 2020-06-05 17:18:25  warn App::Netdisco 2.045006 web

**Comment by romale** [comment] 2020-08-11 15:22
Not work for me too. Starts postgres only
[root@mon ~]# docker ps
CONTAINER ID        IMAGE                                 COMMAND                  CREATED             STATUS              PORTS               NAMES
31215173f6e2        netdisco/netdisco:latest-postgresql   "/usr/local/bin/ne..."   2 minutes ago       Up 2 minutes        5432/tcp            netdisco_netdisco-postgresql_1
[root@mon ~]#

**Comment by KDGundermann** [comment] 2020-11-26 10:45
same problem 
`
Attempting to create directory /home/netdisco/perl5
error: cannot find Netdisco config at /home/netdisco/perl5/lib/perl5/auto/share/dist/App-Netdisco/environments/deployment.yml or /home/netdisco/environments/deployment.yml
error: cannot find Netdisco config at /home/netdisco/perl5/lib/perl5/auto/share/dist/App-Netdisco/environments/deployment.yml or /home/netdisco/environments/deployment.yml
coreos2 overlay # 
`

netdisco/netdisco:latest-web
Created | 2020-10-31 12:22:02

**Comment by inphobia** [comment] 2020-11-26 19:32
see recent comment in #17 , could be a permission issue.

if this doesn't work, could you provide me with your linux distro + version & docker version? no promises, but i'll try to recreate the issue when time permits.

**Comment by AddoSolutions** [comment] 2021-02-07 02:36
Just want to confirm I was able to get this working on a vanilla CentOS 7 install using the instructions provided.  Be sure to pre-create with the proper users/folders/permissions (as described in the root of this Wiki).  But yeah, working like a charm here!

THanks guys!

**Comment by bd5872** [comment] 2021-04-28 18:21
> error: cannot find Netdisco config at /home/netdisco/perl5/lib/perl5/auto/share/dist/App-Netdisco/environments/deployment.yml or /home/netdisco/environments/deployment.yml

The quick fix for this is to just create deployment.yml in the ~/netdisco/config/ directory, either by copying it out of the docker image or pulling the sample config file from the main netdisco git repo.

The larger question is why docker doesn't populate the ~/netdisco/config/ directory with the file from the image, when their docs state that this should happen (https://docs.docker.com/storage/volumes/#populate-a-volume-using-a-container), which could be a issue with specific distros perhaps?

**Comment by jniggemann** [comment] 2021-05-25 14:38
I have deployment.yml in ~/netdisco/config/, but can't access the webinterface nonetheless. All 3 containers are running, nothing notable in the log, netstat on host shows 0.0.0.0:5000 used by docker-proxy (what I assume to be correct).
Yet, going to 127.0.0.1:5000 does simply nothing - the spinner turns forever, no timeout in the browser and nothing in the conainers' logs either.

**Closed** 2021-10-13 11:41 UTC
Labels: waiting for user
